language: c
before_install:
  - sudo apt-get install -yy qemu-system-mips
  - wget --no-check-certificate -O gcc.tgz 'https://www.mips.com/?do-download=linux-x64-mti-bare-metal-2016-05-06'
  - tar -xf gcc.tgz

script:
  - make CROSS_COMPILE=$PWD/mips-mti-elf/2016.05-06/bin/mips-mti-elf- ON_FPGA=y -j4
  - make CROSS_COMPILE=$PWD/mips-mti-elf/2016.05-06/bin/mips-mti-elf- ON_FPGA=y clean
  - make CROSS_COMPILE=$PWD/mips-mti-elf/2016.05-06/bin/mips-mti-elf- ON_FPGA=n -j4
  - echo "Running Tests"
  - timeout 5s qemu-system-mipsel -M mipssim -m 32M -nographic -kernel obj/ucore-kernel-initrd -monitor none -serial file:test.log || true
  - cat test.log
  - grep 'user sh is running!!!' test.log
addons:
  apt:
    update: true
